### ISSUE TITLE
ValueError in create_dataset.py

### ISSUE THREAD

**Issue by julj** [johnmartinsson/bird-species-classification#24]
```
python create_dataset.py --src_dir=<my_src_dir> --dst_dir=<my_dst_dir> --valid_percentage=20
copying sound classes...
splitting train/validation...
Traceback (most recent call last):
  File "create_dataset.py", line 99, in <module>
    main()
  File "create_dataset.py", line 91, in main
    replace=False)
  File "mtrand.pyx", line 1161, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:18155)
ValueError: Cannot take a larger sample than population when 'replace=False'
```

**Comment by johnmartinsson** [comment]
The validation percentage should be in [0,1]. I can see how the naming is confusing and may go through the code and clean it up when I have time. I will raise a separate issue for this.
